name = Home
description = Home page layout
template = home-layout

; Styles
stylesheets[all][] = ../../css/layouts/home/home.layout.css
stylesheets[all][] = ../../css/layouts/home/home.layout.no-query.css

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer