name = Sidebar
description = Interior landing page with sidebar
template = sidebar-layout

; Styles
stylesheets[all][] = ../../css/layouts/sidebar/sidebar.layout.css
stylesheets[all][] = ../../css/layouts/sidebar/sidebar.layout.no-query.css

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First Sidebar
regions[footer]         = Footer